# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

flutter_application_path = '../flutter_edaijia'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'LearnOpenGL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnOpenGL
#  pod 'Flutter'
  pod 'AFNetworking'
  
  install_all_flutter_pods(flutter_application_path)
  
end
